# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-19 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todoDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
